name: Generate GitHub Profile Summary Cards

on:
  schedule: [ { cron: "0 0 * * *" } ]  # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-summary-card-output
          git commit -m "chore: update GitHub profile summary cards"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}
